# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd7a2db14c0026cd5a099a4e8440f9385b0a840221bcf91bb8709436eba0e21d85bfefaa442c991ed071fd0cc8aacf47dc779e4d5e0cff841f5000b77cf9aca

test:
  secret_key_base: 134fcb21bde3d09b0c5d7f96baebecec100ddeb008125170eec51aa443432bc23a39aed45f50aca2e6731dcf4c3d73e89670bdef7a5cdb65aacb90f20d684ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
